# This rule is not used by the project ghops itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to auth.github.odit.services resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ghops
    app.kubernetes.io/managed-by: kustomize
  name: deploykey-viewer-role
rules:
- apiGroups:
  - auth.github.odit.services
  resources:
  - deploykeys
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - auth.github.odit.services
  resources:
  - deploykeys/status
  verbs:
  - get
