---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - auth.github.odit.services
  resources:
  - deploykeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - auth.github.odit.services
  resources:
  - deploykeys/finalizers
  verbs:
  - update
- apiGroups:
  - auth.github.odit.services
  resources:
  - deploykeys/status
  verbs:
  - get
  - patch
  - update
