apiVersion: auth.github.odit.services/v1alpha1
kind: DeployKey
metadata:
  labels:
    app.kubernetes.io/name: ghops
    app.kubernetes.io/managed-by: kustomize
  name: deploykey-sample
spec:
  title: Sample Deploy Key
  owner: odit-services
  repository: ghops
  permission: read
