// Code generated by MockGen. DO NOT EDIT.
// Source: /home/niggl/git/odit.services/ghops/internal/services/sshservice.go
//
// Generated by this command:
//
//	mockgen -source=/home/niggl/git/odit.services/ghops/internal/services/sshservice.go -destination=/home/niggl/git/odit.services/ghops/internal/controller/mocks/sshservice.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSSHService is a mock of SSHService interface.
type MockSSHService struct {
	ctrl     *gomock.Controller
	recorder *MockSSHServiceMockRecorder
	isgomock struct{}
}

// MockSSHServiceMockRecorder is the mock recorder for MockSSHService.
type MockSSHServiceMockRecorder struct {
	mock *MockSSHService
}

// NewMockSSHService creates a new mock instance.
func NewMockSSHService(ctrl *gomock.Controller) *MockSSHService {
	mock := &MockSSHService{ctrl: ctrl}
	mock.recorder = &MockSSHServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSSHService) EXPECT() *MockSSHServiceMockRecorder {
	return m.recorder
}

// GenerateED25519KeyPair mocks base method.
func (m *MockSSHService) GenerateED25519KeyPair() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateED25519KeyPair")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateED25519KeyPair indicates an expected call of GenerateED25519KeyPair.
func (mr *MockSSHServiceMockRecorder) GenerateED25519KeyPair() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateED25519KeyPair", reflect.TypeOf((*MockSSHService)(nil).GenerateED25519KeyPair))
}

// GenerateRSAKeyPair mocks base method.
func (m *MockSSHService) GenerateRSAKeyPair() (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRSAKeyPair")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateRSAKeyPair indicates an expected call of GenerateRSAKeyPair.
func (mr *MockSSHServiceMockRecorder) GenerateRSAKeyPair() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRSAKeyPair", reflect.TypeOf((*MockSSHService)(nil).GenerateRSAKeyPair))
}
